---
- name: Install node.js and npm
  yum: name=npm state=present enablerepo=epel

- name: Install npm modules required by our node.js app
  npm: name={{ item }} global=yes state=present
  with_items:
    "{{ node_npm_modules }}"
