---
- name: file manipulation test
  hosts: app

  vars:
    - theme_name: "Mirage 2"
    - theme_path: "Mirage2/"
    - theme_line: "<theme name=\"{{ theme_name }}\" regex=\".*\" path=\"{{ theme_path }}\" />"

  tasks:
    # force: yes (default) copies file afresh each time (better for initial tests)
    # force: no only copies file if it doesn't exist (better to test idempotence)
    - name: copy test file to server
      copy:
        src: "files/test_file.conf"
        dest: "~/test_file.conf"
        force: no

    - name: comment out line in file
      replace:
        dest: "~/test_file.conf"
        regexp: '(^\s*)(<theme name="Atmire.*/>)'
        replace: '\1<!-- \2 -->'

    - name: insert line into file
      lineinfile:
        dest: "~/test_file.conf"
        insertbefore: '(^\s*)(</themes>)'
        regexp: "(^\\s*)(<theme name=\"{{ theme_name }}\")"
        line: "        {{ theme_line }}"

    - name: check results
      command: "cat ~/test_file.conf"
      changed_when: false
