---
- name: file manipulation test
  hosts: app

  tasks:
    # force: yes (default) copies file afresh each time (better for initial tests)
    # force: no only copies file if it doesn't exist (better to test idempotence)
    - name: copy test file to server
      copy:
        src: "files/test_file.conf"
        dest: "~/test_file.conf"
        force: no

    - name: comment out line in file
      replace:
        dest: "~/test_file.conf"
        regexp: '(^\s*)(<theme name="Atmire.*/>)'
        replace: '\1<!-- \2 -->'

    - name: insert line into file
      lineinfile:
        dest: "~/test_file.conf"
        insertbefore: '(^\s*)(</themes>)'
        regexp: '(^\s*)(<theme name="Mirage 2")'
        line: '        <theme name="Mirage 2" regex=".*" path="Mirage2/" />'

    - name: check results
      command: "cat ~/test_file.conf"
