---
  - hosts: all
    become: yes
    tasks:
      - name: Ensure NTP (for time synchronization) is installed.
        apt: name=ntp state=present
      - name: Ensure NTP is running.
        service: name=ntp state=started enabled=yes
